/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.automattic.android.applystyle

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class ApplyStylePlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin '${ApplyStylePlugin.PLUGIN_NAME}'")
            }
        }
    }

    companion object {
        const val PLUGIN_NAME = "a8c-apply-style-gradle-plugin"
    }
}
