/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.automattic.android.applystyle

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the plugin.
 */
class ApplystylePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply(ApplyStylePlugin.PLUGIN_NAME)

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
